### ISSUE TITLE
About Training and Weights

### ISSUE THREAD

**Issue by jiaqixuac** [jel-lambda/new-Transweather#1]
Hi,

Thank you for your nice work.

I want to know if the pre-trained weights are available.
Besides, I want to know what are the .txt files for train and val in ```train.py```.
```
python train.py  -train_batch_size 32 -exp_name Transweather -epoch_start 0 -num_epochs 250
```

Thanks

**Comment by x33rak** [comment]
did you manage to get access to the pre-trained weights?

**Comment by jel-lambda** [comment]
Sorry for the late response. If it is still helpful, please check here, the original repository. (https://github.com/jeya-maria-jose/TransWeather)
